extern NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_DESCRIPTOR_ID;
extern NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_DESCRIPTOR_UUID;
extern NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_CHARACTERISTIC_ID;
extern NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_CHARACTERISTIC_UUID;
extern NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_SERVICE_ID;
extern NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_SERVICE_UUID;
extern NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_DEVICE_ID;
extern NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_VALUE;
