NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_DESCRIPTOR_ID = @"id";
NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_DESCRIPTOR_UUID = @"uuid";
NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_CHARACTERISTIC_ID = @"characteristicID";
NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_CHARACTERISTIC_UUID = @"characteristicUUID";
NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_SERVICE_ID = @"serviceID";
NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_SERVICE_UUID = @"serviceUUID";
NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_DEVICE_ID = @"deviceID";
NSString * const BLEMULATOR_DESCRIPTOR_RESPONSE_VALUE = @"value";
